- name: Setup base software
  hosts: localhost

  tasks:
    - name: Install package foo from repo
      become: true
      community.general.pacman:
        name:
          - git
          - base-devel
          - archlinux-keyring
        state: present

    - name: Check if yay is installed
      command: which yay
      register: yay_check
      ignore_errors: true
      changed_when: false

    - name: Download yay
      register: yay_download
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /tmp/yay
      when: yay_check.rc != 0

    - name: Install yay
      command: makepkg -si
      args:
        chdir: /tmp/yay
      when: yay_check.rc != 0 and yay_download.changed

    - name: Fonts
      yay:
        name:
          - adobe-source-code-pro-fonts
          - noto-fonts-emoji
          - otf-font-awesome
          - ttf-droid
          - ttf-fira-code
          - ttf-jetbrains-mono
          - ttf-jetbrains-mono-nerd
        state: present

    - name: Hyprland
      yay:
        name:
          - hyprcursor
          - hyprutils
          - aquamarine
          - hypridle
          - hyprlock
          - hyprland
          - pyprland
          - kitty
        state: present
