- name: Setup base software
  hosts: localhost
  become: true

  tasks:
    - name: Install package foo from repo
      community.general.pacman:
        name:
         - git
         - base-devel
         - archlinux-keyring
        state: present

    - name: Fonts
      yay:
        name:
          - adobe-source-code-pro-fonts 
          - noto-fonts-emoji
          - otf-font-awesome 
          - ttf-droid 
          - ttf-fira-code
          - ttf-jetbrains-mono 
          - ttf-jetbrains-mono-nerd
        state: present

    - name: Hyprland
      yay:
        name:
          - hyprcursor
          - hyprutils
          - aquamarine
          - hypridle
          - hyprlock
          - hyprland
          - pyprland
          - kitty
        state: present
      